### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by princemaple**
Caddy v0.9.2 was released and more plugins were built.

### CODE REVIEW

**Comment by princemaple** [comment]
@killianbrackey ping

**Comment by kilpatty** [comment]
Sorry about the delay! Working on this now :)

**Comment by princemaple** [comment]
No worries, it seems that there's going to be another release this week.

**Comment by killianbrackey** [comment]
@princemaple It also appears that the caddy build server isn't working (building middlewares) which is why these builds keep failing.

**Comment by princemaple** [comment]
FYI 0.9.3 released

**Comment by jlgeering** [comment]
https://github.com/mholt/caddy/releases/tag/v0.9.3

**Comment by killianbrackey** [comment]
Caddy middleware build server is fixed so we could get this fixed and updated now!

https://github.com/ZZROTDesign/alpine-caddy/releases/tag/v0.9.3

Thanks again @princemaple 💯

**Pull request closed without merging**
