### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by princemaple**
Caddy 0.9.1 is released with more plugins supporting 0.9+ now.

### CODE REVIEW

**Comment by princemaple** [comment]
oh, maybe you left it as 0.9 on purpose? let me know if you want the `.1` gone

**Comment by killianbrackey** [comment]
@princemaple Thanks again! We try to keep the version current with the caddy version so if you could change that back and also add the newest changes to master (made a few changes to the travis.yml as they finally updated travis' docker engine version) your tests should pass and we can get this merged 👍

**Comment by princemaple** [comment]
Yep will do that when I get back to my computer.
~~Caddy build server isn't serving the correct bundle at the moment anyway. I'll make a note when everything is ready.~~ **Note!**

**Comment by killianbrackey** [comment]
Ok perfect.  I gave it a try in our develop branch and got that failure: https://travis-ci.org/ZZROTDesign/alpine-caddy/builds/153160469

**Comment by princemaple** [comment]
@killianbrackey removed the `.1` and rebased to current master

**Comment by princemaple** [comment]
And the caddy download server should be ready now.

**Comment by killianbrackey** [comment]
Thanks! Merged and re-tagged the v0.9 release so the build on Docker Hub will be the most recent.

**Pull request merged**
